### ISSUE TITLE
Different behavior on py2 and py3

### ISSUE THREAD

**Issue by adrian-dankiv** [gr0und-s3ct0r/niet#1] opened 2018-04-10 13:37 UTC
There is quoting only in py3:
```
$ echo '{"a": ["foo", "b ar", "baz"]}' > tmp.json
$ python2 -m niet tmp/tmp.json a
foo b ar baz
$ python3 -m niet tmp/tmp.json a
'foo' 'b ar' 'baz'
```

Also, I think that the best variant is optional quoting:
`foo 'b ar' baz`
Because in another way I must write like this:
`VAR=$(echo ${VAR} | sed s/\'//g)`

**Comment by 4383** [comment] 2018-04-10 14:04
Hi @adrian-dankiv thanks for this issue!

We will investigate on!

**Comment by dj4ngo** [comment] 2018-04-10 22:28
Hi, thank you for your remark ! 
I can't reproduce it on my side, I've get never quotes, I'll try to reproduce it on an other environment. 

Could you tell me your python3 version ? 

For your suggestion having optional quotes or even adding a '\' before the space won't solve the problem regarding the way you are parsing it (for example with a for loop). We intend to add an optional trigger on the cli to apply or not the quotes for all results. Since you seems to be in this case,  I'll see with @4383 to implement it as soon as possible.

**Comment by 4383** [comment] 2018-04-11 19:54
Hi @adrian-dankiv!

Can you add some informations please.
What Python version is precisely used for python 2 and 3? 
- `python2 --version` 
- `python3 --version` 

Thank you

**Comment by 4383** [comment] 2018-04-11 21:43
@adrian-dankiv @ADR-007 new development version are available!

You can try it by using:
```shell
$ git clone https://github.com/gr0und-s3ct0r/niet.git
$ cd niet
$ python setup.py install # or develop
```
Feedback are welcomes!
Thanks

**Comment by dj4ngo** [comment] 2018-04-27 13:48
Hi @ADR-007 @adrian-dankiv, I just pushed a lot of new features that should solve the issue and match your needs.

**Comment by ADR-007** [comment] 2018-04-27 13:52
Now all works fine. Thank you!

**Comment by 4383** [comment] 2018-04-27 14:10
Thank you @ADR-007!

The [release 1.2.0](https://github.com/gr0und-s3ct0r/niet/releases/tag/1.2.0) resolve the behavior.

We can close this issue.

**Closed by 4383** 2018-04-27 14:10 UTC
Labels: bug
